### PR TITLE
Refactor docker build for the .NET performer

### PR DESCRIPTION
**Pull request by SecureCake**
Changes
-------
These changes are to accomodate the Dockerfile changes in transactions-fit-performer for building a docker image of the .NET performer. Performer patch: https://review.couchbase.org/c/transactions-fit-performer/+/207718

### CODE REVIEW

**Review by Couch-Matt — APPROVED** [review]
Am I correct in believing this will use the 2 new Dockerfiles without any FIT Jenkinsfile changes? Does this include the standard runs where we provide no specific -v or -c params?

**Comment by SecureCake** [comment]
If the build is always triggered with "./gradlew buildPerformer --args="..."" then yes. 
However IF anything used to directly reference "transactions-fit-performer/performers/dotnet/Couchbase.Transaction.FitPerformer/Dockerfile", that will break since the file doesn't exist anymore. 
As far as I've looked I haven't seen anything doing that,

**Comment by Couch-Matt** [comment]
Nope, we solely reference the gradle scripts so all good on the Jenkins side. Cheers

**Comment by SecureCake** [comment]
I can't add @programmatix as a reviewer so tagging here

**Review by programmatix — APPROVED** [review]
Great stuff!  Improving how the .NET performer is built has been on the cards for a very long time.

**Pull request merged**
